// GENERATED FILE - DO NOT EDIT.
// Generated by generate_entry_points.py using data from gl.xml.
//
// Copyright 2019 The ANGLE Project Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// entry_points_gl_4_6_autogen.cpp:
//   Defines the GL 4.6 entry points.

#include "libGL/entry_points_gl_4_6_autogen.h"

#include "libANGLE/Context.h"
#include "libANGLE/Context.inl.h"
#include "libANGLE/entry_points_utils.h"
#include "libANGLE/validationEGL.h"
#include "libANGLE/validationES.h"
#include "libANGLE/validationES1.h"
#include "libANGLE/validationES2.h"
#include "libANGLE/validationES3.h"
#include "libANGLE/validationES31.h"
#include "libANGLE/validationESEXT.h"
#include "libANGLE/validationGL46_autogen.h"
#include "libGLESv2/global_state.h"

namespace gl
{
void GL_APIENTRY MultiDrawArraysIndirectCount(GLenum mode,
                                              const void *indirect,
                                              GLintptr drawcount,
                                              GLsizei maxdrawcount,
                                              GLsizei stride)
{
    EVENT("(GLenum mode = 0x%X, const void *indirect = 0x%016" PRIxPTR
          ", GLintptr drawcount = %llu, GLsizei maxdrawcount = %d, GLsizei stride = %d)",
          mode, (uintptr_t)indirect, static_cast<unsigned long long>(drawcount), maxdrawcount,
          stride);

    Context *context = GetValidGlobalContext();
    if (context)
    {
        ANGLE_CAPTURE(MultiDrawArraysIndirectCount, context, mode, indirect, drawcount,
                      maxdrawcount, stride);
        if (context->skipValidation() ||
            ValidateMultiDrawArraysIndirectCount(context, mode, indirect, drawcount, maxdrawcount,
                                                 stride))
        {
            context->multiDrawArraysIndirectCount(mode, indirect, drawcount, maxdrawcount, stride);
        }
    }
}

void GL_APIENTRY MultiDrawElementsIndirectCount(GLenum mode,
                                                GLenum type,
                                                const void *indirect,
                                                GLintptr drawcount,
                                                GLsizei maxdrawcount,
                                                GLsizei stride)
{
    EVENT("(GLenum mode = 0x%X, GLenum type = 0x%X, const void *indirect = 0x%016" PRIxPTR
          ", GLintptr drawcount = %llu, GLsizei maxdrawcount = %d, GLsizei stride = %d)",
          mode, type, (uintptr_t)indirect, static_cast<unsigned long long>(drawcount), maxdrawcount,
          stride);

    Context *context = GetValidGlobalContext();
    if (context)
    {
        ANGLE_CAPTURE(MultiDrawElementsIndirectCount, context, mode, type, indirect, drawcount,
                      maxdrawcount, stride);
        if (context->skipValidation() ||
            ValidateMultiDrawElementsIndirectCount(context, mode, type, indirect, drawcount,
                                                   maxdrawcount, stride))
        {
            context->multiDrawElementsIndirectCount(mode, type, indirect, drawcount, maxdrawcount,
                                                    stride);
        }
    }
}

void GL_APIENTRY PolygonOffsetClamp(GLfloat factor, GLfloat units, GLfloat clamp)
{
    EVENT("(GLfloat factor = %f, GLfloat units = %f, GLfloat clamp = %f)", factor, units, clamp);

    Context *context = GetValidGlobalContext();
    if (context)
    {
        ANGLE_CAPTURE(PolygonOffsetClamp, context, factor, units, clamp);
        if (context->skipValidation() || ValidatePolygonOffsetClamp(context, factor, units, clamp))
        {
            context->polygonOffsetClamp(factor, units, clamp);
        }
    }
}

void GL_APIENTRY SpecializeShader(GLuint shader,
                                  const GLchar *pEntryPoint,
                                  GLuint numSpecializationConstants,
                                  const GLuint *pConstantIndex,
                                  const GLuint *pConstantValue)
{
    EVENT("(GLuint shader = %u, const GLchar *pEntryPoint = 0x%016" PRIxPTR
          ", GLuint numSpecializationConstants = %u, const GLuint *pConstantIndex = 0x%016" PRIxPTR
          ", const GLuint *pConstantValue = 0x%016" PRIxPTR ")",
          shader, (uintptr_t)pEntryPoint, numSpecializationConstants, (uintptr_t)pConstantIndex,
          (uintptr_t)pConstantValue);

    Context *context = GetValidGlobalContext();
    if (context)
    {
        ANGLE_CAPTURE(SpecializeShader, context, shader, pEntryPoint, numSpecializationConstants,
                      pConstantIndex, pConstantValue);
        if (context->skipValidation() ||
            ValidateSpecializeShader(context, shader, pEntryPoint, numSpecializationConstants,
                                     pConstantIndex, pConstantValue))
        {
            context->specializeShader(shader, pEntryPoint, numSpecializationConstants,
                                      pConstantIndex, pConstantValue);
        }
    }
}
}  // namespace gl
